# ---------------------------------------------------------------
# 插件 (Plugins)
# ---------------------------------------------------------------
plugins:
  - jekyll-feed # 生成 RSS Feed，方便订阅者
  - jekyll-seo-tag # 增强 SEO，自动生成 Open Graph 和 Twitter Card 元标签

# ---------------------------------------------------------------
# 站点设置 (Site Settings)
# ---------------------------------------------------------------
lang: zh-CN # 站点语言设置为简体中文
title: Anton的技术博客 # 你的博客标题
email: anton_we@outlook.com # 你的联系邮箱，可选
description: >- # 你的博客描述，会显示在搜索引擎结果中
  欢迎来到我的博客，和我探寻科技的意义。

url: "https://T2XX.github.io" # 只写域名部分，不带仓库名
baseurl: "/T2XX" # 必须是你的仓库名，前面带斜杠

permalink: /:year/:month/:day/:title/ # 优雅的 URL 结构

# Jekyll 设置
markdown: kramdown # 或 commonmark, GFM
highlighter: rouge # 代码高亮
kramdown:
  input: GFM # GitHub Flavored Markdown
  syntax_highlighter: rouge
# 评论系统配置 (Utterances)
# 这是一个基于 GitHub Issues 的评论系统
comments:
  utterances:
    repo: "T2XX/T2XX" # 替换为你的 GitHub 仓库名，格式为 "用户名/仓库名"
    issue_term: "pathname" # 可以是 "pathname", "url", "title", "og:title"
    theme: "github-light" # 主题：github-light, github-dark, preferred-color-scheme, dark_dimmed, photon-dark, starry-night, raddiwag, grubox
    # 如果你的仓库是私有的或者只想特定用户评论，请查阅 Utterances 文档
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - .vscode
defaults:
  - scope:
      path: "" # 整个站点
    values:
      layout: "default" # 默认布局
  - scope:
      path: "_posts" # 针对 _posts 目录
      type: "posts"
    values:
      layout: "post" # 文章使用 post 布局